name: Pytest

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    name: Run Pytest
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5.1.0
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.lock
        pip install pytest

    - name: Run Pytest
      run: pytest tests/
