name: Super Linter

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.4

      - name: Set up Super-Linter
        uses: super-linter/super-linter@v6.4.1
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}

      - name: Run Super-Linter
        run: ./bin/run-linter
